export const getSatelliteCountryName = (code) => {
  switch (code) {
    case "AB":
      return "阿拉伯卫星通信组织";
    case "ABS":
      return "亚洲广播卫星";
    case "AC":
      return "亚洲卫星电讯公司";
    case "ALG":
      return "阿尔及利亚";
    case "ANG":
      return "安哥拉";
    case "ARGN":
      return "阿根廷";
    case "ASRA":
      return "奥地利";
    case "AUS":
      return "澳大利亚";
    case "AZER":
      return "阿塞拜疆";
    case "BEL":
      return "比利时";
    case "BELA":
      return "白俄罗斯";
    case "BERM":
      return "百慕大";
    case "BGD":
      return "孟加拉国";
    case "BHUT":
      return "不丹王国";
    case "BOL":
      return "玻利维亚";
    case "BRAZ":
      return "巴西";
    case "BUL":
      return "保加利亚";
    case "CA":
      return "加拿大";
    case "CHBZ":
      return "中国/巴西";
    case "CHLE":
      return "智利";
    case "CIS":
      return "前苏联";
    case "COL":
      return "哥伦比亚";
    case "CRI":
      return "哥斯达黎加共和国";
    case "CZCH":
      return "捷克";
    case "DEN":
      return "丹麦";
    case "ECU":
      return "厄瓜多尔";
    case "EGYP":
      return "埃及";
    case "ESA":
      return "欧洲太空总署";
    case "ESRO":
      return "欧洲空间研究组织";
    case "EST":
      return "爱沙尼亚";
    case "EUME":
      return "欧洲气象卫星开发组织";
    case "EUTE":
      return "欧洲电信卫星组织";
    case "FGER":
      return "法国/德国";
    case "FIN":
      return "芬兰";
    case "FR":
      return "法国";
    case "FRIT":
      return "法国/意大利";
    case "GER":
      return "德国";
    case "GHA":
      return "加纳共和国";
    case "GLOB":
      return "全球星";
    case "GREC":
      return "希腊";
    case "GRSA":
      return "希腊/沙特阿拉伯";
    case "GUAT":
      return "危地马拉";
    case "HUN":
      return "匈牙利";
    case "IM":
      return "国际移动卫星组织(INMARSAT)";
    case "IND":
      return "印度";
    case "INDO":
      return "印尼";
    case "IRAN":
      return "伊朗";
    case "IRAQ":
      return "伊拉克";
    case "IRID":
      return "IRID";
    case "ISRA":
      return "以色列";
    case "ISRO":
      return "印度空间研究组织";
    case "ISS":
      return "国际空间站";
    case "IT":
      return "意大利";
    case "ITSO":
      return "国际电信卫星组织";
    case "JPN":
      return "日本";
    case "KAZ":
      return "哈萨克斯坦";
    case "KEN":
      return "肯尼亚";
    case "LAOS":
      return "老挝";
    case "LKA":
      return "斯里兰卡";
    case "LTU":
      return "立陶宛";
    case "LUXE":
      return "卢森堡";
    case "MA":
      return "摩洛哥";
    case "MALA":
      return "马来西亚";
    case "MEX":
      return "墨西哥";
    case "MMR":
      return "缅甸";
    case "MNG":
      return "蒙古";
    case "MUS":
      return "毛里求斯";
    case "NATO":
      return "北大西洋公约组织";
    case "NETH":
      return "荷兰";
    case "NICO":
      return "新图标";
    case "NIG":
      return "尼日利亚";
    case "NKOR":
      return "朝鲜";
    case "NOR":
      return "挪威";
    case "NPL":
      return "尼泊尔";
    case "NZ":
      return "新西兰";
    case "O3B":
      return "O3b Networks公司";
    case "ORB":
      return "ORBCOMM卫星公司";
    case "PAKI":
      return "巴基斯坦";
    case "PERU":
      return "秘鲁";
    case "POL":
      return "波兰";
    case "POR":
      return "葡萄牙";
    case "PRC":
      return "中国";
    case "PRY":
      return "巴拉圭";
    case "PRES":
      return "中国/欧洲航天局";
    case "QAT":
      return "卡塔尔的状态";
    case "RASC":
      return "非洲区域卫星通信组织";
    case "ROC":
      return "台湾";
    case "ROM":
      return "罗马尼亚";
    case "RP":
      return "菲律宾";
    case "RWA":
      return "卢旺达";
    case "SAFR":
      return "南非";
    case "SAUD":
      return "沙特阿拉伯";
    case "SDN":
      return "苏丹";
    case "SEAL":
      return "Sea Launch公司";
    case "SES":
      return "SES电信公司";
    case "SGJP":
      return "新加坡/日本";
    case "SING":
      return "新加坡";
    case "SKOR":
      return "韩国";
    case "SPN":
      return "西班牙";
    case "STCT":
      return "新加坡/台湾";
    case "SVN":
      return "斯洛文尼亚";
    case "SWED":
      return "瑞典";
    case "SWTZ":
      return "瑞士";
    case "TBD":
      return "待定";
    case "THAI":
      return "泰国";
    case "TMMC":
      return "土库曼斯坦/摩纳哥";
    case "TUN":
      return "突尼斯共和国";
    case "TURK":
      return "土耳其";
    case "UAE":
      return "阿拉伯联合酋长国";
    case "UK":
      return "英国";
    case "UKR":
      return "乌克兰";
    case "URY":
      return "乌拉圭";
    case "US":
      return "美国";
    case "USBZ":
      return "美国/巴西";
    case "VENZ":
      return "委内瑞拉";
    case "VTNM":
      return "越南";
    case "UNK":
      return "未知";
  }
  return code;
};
